version: "3.9"

services:
  app:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 8080:80
  mysql:
    image: mysql:5.7.41-debian
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=login_register
